export const list = [
    {
      title: "Дубаї, Обʼєднані Арабські Емірати",
      imgSrc: [
        "https://a0.muscache.com/im/pictures/miso/Hosting-721540609203378406/original/9dfaf7d6-40f2-4673-b468-7c5ab3147f86.jpeg?im_w=1200",
        "https://a0.muscache.com/im/pictures/miso/Hosting-721540609203378406/original/cc2a2d85-d879-465c-9154-0574629527cd.jpeg?im_w=720",
        "https://a0.muscache.com/im/pictures/miso/Hosting-721540609203378406/original/b774c2ea-f956-49c7-8ad4-3b744c6b9cfb.jpeg?im_w=720",
      ],
      rating: "5",
      category: "0",
      desc: "На відстані 3836 кілометра",
      price: "224",
      data: "11-16 груд.",
    },
    {
      title: "Калґарі, Канада",
      imgSrc: [
        "https://a0.muscache.com/im/pictures/miso/Hosting-855265289472667062/original/99f4d83b-7de8-467a-be43-4a5ddd184b24.jpeg?im_w=1200",
        "https://a0.muscache.com/im/pictures/miso/Hosting-855265289472667062/original/2cddcc8e-0a52-40ea-9d40-8a30ed11ed92.jpeg?im_w=720",
        "https://a0.muscache.com/im/pictures/miso/Hosting-855265289472667062/original/662181dc-0a23-42c6-8792-b45c6c764610.jpeg?im_w=720",
      ],
      rating: "5",
      category: "1",
      desc: "На відстані 8117 кілометра",
      price: "109",
      data: "10-15 груд.",
    },
    {
      title: "Дублін, County Dublin, Ірландія",
      imgSrc: [
        "https://a0.muscache.com/im/pictures/miso/Hosting-892636584500492829/original/bd3b69fd-8b16-43c6-ae7c-758da919259b.jpeg?im_w=480",
        "https://a0.muscache.com/im/pictures/miso/Hosting-892636584500492829/original/c45bf8cf-2ad6-4930-8c9f-f6f3c992aedd.jpeg?im_w=480",
        "https://a0.muscache.com/im/pictures/miso/Hosting-892636584500492829/original/828bf472-0ba4-48d4-8f6b-b7b6e64c5ece.jpeg?im_w=720",
      ],
      rating: "5",
      category: "2",
      desc: "На відстані 2123 кілометра",
      price: "16654",
      data: "20-25 лист.",
    },
    {
      title: "Париж, Франція",
      imgSrc: [
        "https://a0.muscache.com/im/pictures/prohost-api/Hosting-45967096/original/c04c76cb-285c-43a2-a537-889b18be6e52.jpeg?im_w=720",
        "https://a0.muscache.com/im/pictures/prohost-api/Hosting-45967096/original/984b2635-c05a-4d48-ac29-6f1523e5f96d.jpeg?im_w=1200",
        "https://a0.muscache.com/im/pictures/prohost-api/Hosting-45967096/original/55597a03-4b29-463f-b6c3-0803774035ae.jpeg?im_w=720",
      ],
      rating: "5",
      category: "3",
      desc: "На відстані 1573 кілометра",
      price: "1350",
      data: "1-6 груд.",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },
    {
      title: "",
      imgSrc: [
        "",
        "",
        "",
      ],
      rating: "",
      category: "",
      desc: "На відстані  кілометра",
      price: "",
      data: "",
    },

  ];